//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Assignment.TicketServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TicketServiceReference.ILoadTextService")]
    public interface ILoadTextService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadTextService/GetTicketInfo", ReplyAction="http://tempuri.org/ILoadTextService/GetTicketInfoResponse")]
        System.Data.DataSet GetTicketInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadTextService/GetTicketInfo", ReplyAction="http://tempuri.org/ILoadTextService/GetTicketInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTicketInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoadTextServiceChannel : Final_Assignment.TicketServiceReference.ILoadTextService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadTextServiceClient : System.ServiceModel.ClientBase<Final_Assignment.TicketServiceReference.ILoadTextService>, Final_Assignment.TicketServiceReference.ILoadTextService {
        
        public LoadTextServiceClient() {
        }
        
        public LoadTextServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadTextServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadTextServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadTextServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetTicketInfo() {
            return base.Channel.GetTicketInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTicketInfoAsync() {
            return base.Channel.GetTicketInfoAsync();
        }
    }
}
